//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using Entities;
using System.ComponentModel.Composition;


namespace DAL
{
    [Export(typeof(TestContext)), PartCreationPolicy(CreationPolicy.NonShared)]
    public partial class TestContext : ObjectContext
    {
        public const string ConnectionString = "name=TestContext";
        public const string ContainerName = "TestContext";
    
        #region Constructors
    
        public TestContext()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public TestContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public TestContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<customer> customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<customer>("customers")); }
        }
        private ObjectSet<customer> _customers;

        #endregion
    }
}
